name: cvapps
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.0
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - opencv
  - pip
  - pip:
      - jupyter
      - notebook
      - tqdm
      - imageio
      - pillow
