name: cvapps
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.0
  - scipy=1.6.2
  - opencv=4.5.2
  - matplotlib=3.4.2
  - h5py=3.3.0
  - pillow=8.3.1
  - ipython
  - ffmpeg
  - pip
  - pip:
    - ipdb
    - pylint
    - astroid
    - isort
    - toml